"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { ApplicantIntelligence, PropertyMatch } from "@/types/domain";
import { getApplicantIntelligence, getClientWorkflow, postClientMatches, postSaveProperty, postWorkflowPreferences, type WorkflowState } from "@/lib/api";

const lifestyleOptions = ["Transport", "Gym", "Pet friendly", "Garden", "Balcony", "Workspace", "River view", "Parking", "Concierge", "School proximity"];

export function ClientDashboard() {
  const [intel, setIntel] = useState<ApplicantIntelligence | null>(null);
  const [step, setStep] = useState(0);
  const [complete, setComplete] = useState(false);
  const [budget, setBudget] = useState("£2,500–£2,800");
  const [areas, setAreas] = useState("Canary Wharf, Stratford");
  const [bedrooms, setBedrooms] = useState("2 bedrooms");
  const [lifestyle, setLifestyle] = useState(["Transport", "Balcony", "Gym", "Concierge"]);
  const [saved, setSaved] = useState<string[]>([]);
  const [clientMatches, setClientMatches] = useState<PropertyMatch[]>([]);
  const [matchLoading, setMatchLoading] = useState(false);
  const [workflow, setWorkflow] = useState<WorkflowState | null>(null);

  useEffect(() => { Promise.all([getApplicantIntelligence("A-DEMO-SARAH"), getClientWorkflow()]).then(([intelligence, state]) => { setIntel(intelligence); setWorkflow(state); setSaved(state.saved_properties.map((item) => item.property_id)); }).catch(() => undefined); }, []);
  const matches = clientMatches.length ? clientMatches : intel?.top_matches || [];
  function toggleLifestyle(value: string) { setLifestyle((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]); }
  async function toggleSaved(id: string) { try { const shouldSave = !saved.includes(id); const result = await postSaveProperty(id, shouldSave); const next = shouldSave ? [...saved, id] : saved.filter((item) => item !== id); setSaved(next); setWorkflow((current) => current ? { ...current, saved_properties: result.status === "saved" ? [...current.saved_properties.filter((item) => item.property_id !== id), { saved_id: `local-${id}`, property_id: id, created_at: new Date().toISOString() }] : current.saved_properties.filter((item) => item.property_id !== id) } : current); } catch { /* property card remains unchanged when the API is unavailable */ } }
  async function completeQuestionnaire() { setMatchLoading(true); try { const numericBudget = Number(budget.replace(/[^0-9]/g, "").slice(-4)) || 2800; const preferences = { budget_max: numericBudget, preferred_areas: areas, bedrooms_required: Number(bedrooms.charAt(0)), amenities_preferences: lifestyle.map((item) => item.toLowerCase().replaceAll(" ", "-")).join("|"), move_in_date: "2026-09-15" }; const [matchResults] = await Promise.all([postClientMatches(preferences), postWorkflowPreferences({ applicant_id: "A-DEMO-SARAH", ...preferences })]); setClientMatches(matchResults); setWorkflow(await getClientWorkflow()); setComplete(true); } finally { setMatchLoading(false); } }
  return <>
    <section className="client-welcome"><div><div className="eyebrow">Your search · Sarah Mitchell</div><h1>Find a place that fits.</h1><p className="lead">Recommendations shaped around your budget, priorities and the way you live.</p></div><div className="profile-completion"><span>Profile completion</span><strong>{complete ? "100%" : "70%"}</strong><div className="bar"><span style={{ width: complete ? "100%" : "70%" }} /></div></div></section>
    {!complete ? <section className="onboarding card" id="profile"><div className="onboarding-side"><span className="step-count">0{step + 1} / 03</span><h2>Tell us what matters to you.</h2><p className="muted">A few preferences help us rank homes more usefully. You can change them any time.</p></div><div className="onboarding-form">{step === 0 && <><label>What is your monthly budget?<select value={budget} onChange={(event) => setBudget(event.target.value)}><option>£1,800–£2,200</option><option>£2,200–£2,500</option><option>£2,500–£2,800</option><option>£2,800–£3,200</option></select></label><label>Which areas are you considering?<input value={areas} onChange={(event) => setAreas(event.target.value)} /></label><label>How many bedrooms do you need?<select value={bedrooms} onChange={(event) => setBedrooms(event.target.value)}><option>1 bedroom</option><option>2 bedrooms</option><option>3 bedrooms</option></select></label></>}{step === 1 && <><label>When are you looking to move?<select><option>September 2026</option><option>October 2026</option><option>Flexible</option></select></label><label>What matters most to you?<div className="preference-grid">{lifestyleOptions.map((option) => <button type="button" className={`preference-option ${lifestyle.includes(option) ? "selected" : ""}`} onClick={() => toggleLifestyle(option)} key={option}>{option}</button>)}</div></label></>}{step === 2 && <div className="questionnaire-review"><span className="badge high">Ready to personalise</span><h2>Your search profile</h2><p><strong>{budget}</strong> · {areas} · {bedrooms}</p><div className="split">{lifestyle.map((item) => <span className="tag" key={item}>{item}</span>)}</div><p className="muted">We’ll use these preferences alongside your existing activity to rank your matches.</p></div>}<div className="form-actions">{step > 0 && <button className="button secondary" onClick={() => setStep(step - 1)}>Back</button>}<button className="button" onClick={() => step < 2 ? setStep(step + 1) : completeQuestionnaire()} disabled={matchLoading}>{matchLoading ? "Ranking your matches…" : step < 2 ? "Continue" : "See my matches"}</button></div></div></section> : <>
      <section className="client-profile-strip" id="profile"><div><span className="eyebrow">Your profile</span><h2>Sarah Mitchell</h2><p className="muted">{budget} · {areas} · {bedrooms} · moving September 2026</p></div><button className="button secondary" onClick={() => setComplete(false)}>Edit preferences</button><div className="profile-tags">{lifestyle.map((item) => <span className="tag" key={item}>{item}</span>)}</div></section>
      <section id="matches"><div className="section-heading"><div><div className="eyebrow">Personalised for you</div><h2>Your property matches</h2><p className="muted">Ranked from your stated preferences and recorded property behaviour.</p></div><span className="badge">{matches.length} strong matches</span></div><div className="client-property-grid">{matches.map((match) => <ClientPropertyCard key={match.property.property_id} match={match} saved={saved.includes(match.property.property_id)} onSave={() => toggleSaved(match.property.property_id)} />)}</div></section>
      <section className="client-bottom-grid"><div className="card" id="saved"><div className="eyebrow">Saved properties</div><h2>{saved.length ? `${saved.length} property${saved.length === 1 ? "" : "ies"} saved` : "Keep your shortlist together"}</h2><p className="muted">Save a property to come back to it when you are ready.</p></div><div className="card" id="viewings"><div className="eyebrow">Viewings</div>{workflow?.viewing_requests.length ? workflow.viewing_requests.slice(0, 2).map((viewing) => <div className="workflow-row" key={viewing.request_id}><strong>{viewing.property_id}</strong><span>{viewing.status.replaceAll("_", " ")}</span></div>) : <><h2>Ready when you are</h2><p className="muted">Request a viewing from any property detail page and the agency will follow up.</p></>}</div><div className="card"><div className="eyebrow">Applications</div>{workflow?.applications.length ? workflow.applications.slice(0, 2).map((application) => <div className="workflow-row" key={application.application_id}><strong>{application.property_id}</strong><span>{application.status.replaceAll("_", " ")}</span></div>) : <p className="muted">Your application progress will appear here.</p>}</div></section>
    </>}
  </>;
}

function ClientPropertyCard({ match, saved, onSave }: { match: PropertyMatch; saved: boolean; onSave: () => void }) {
  const property = match.property;
  return <article className="client-property-card"><Link href={`/client/properties/${property.property_id}`} className="property-visual"><span>Property visual</span><small>{property.area} · synthetic listing</small></Link><div className="property-card-body"><div className="property-card-heading"><div><span className="eyebrow">{property.property_type} · {property.area}</span><h3>{property.bedrooms}-bedroom home</h3></div><strong className="match-score">{match.match_score}%<small>match</small></strong></div><p className="rent">£{property.rent_pcm.toLocaleString()} <span>pcm</span></p><div className="property-meta"><span>{property.bedrooms} beds</span><span>{property.furnished ? "Furnished" : "Unfurnished"}</span><span>{property.size_sqft} sq ft</span></div><p className="match-reason">{match.explanation.positives.slice(0, 2).join(" · ")}</p><div className="property-card-actions"><Link href={`/client/properties/${property.property_id}`} className="text-link">View details →</Link><button className="save-button" onClick={onSave} aria-label={saved ? "Remove saved property" : "Save property"}>{saved ? "Saved" : "Save"}</button></div></div></article>;
}
